services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: passwd
    ports:
      - '5432'
    restart: always

  backend:
    build: .
    depends_on:
      - postgres
    ports:
      - '8080'
    restart: always