services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=superpatos'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=a'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: backend
    build: .
    ports:
      - '8080:8080'
    restart: 'always'

volumes:
  pgdata: {}